# ---------------------------------------------------------------------------
# Trivadis - Part of Accenture, Platform Factory - Transactional Data Platform
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ---------------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2022.03.30
# Revision...: --
# Purpose....: Docker compose file to create a 389 Directory Server
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------

version: '3'
services:
# LDAP service
  389ds:
    image: oehrlis/389ds
    container_name: 389ds
    hostname: 389ds
    networks:
      default:
        aliases: 
          - 389ds.trivadislabs.com
    dns_search: trivadislabs.com
    restart: unless-stopped
    volumes:
      - ./dirsrv:/data
    ports:
      - "1389:3389"
      - "1636:3636"
    # environment:
    #   INSTANCE_INIT: /u01/config
    #   ORACLE_SID: TCMU01

# - EOF -----------------------------------------------------------------
